### ISSUE TITLE
Any way to reorder pages, delete pages, or move anything between pages (Feature Request)

### ISSUE THREAD

**Issue by robertskmiles** [edemaine/cocreate#119]
We're using cocreate as a public whiteboard in a shared virtual space. Currently we have a large piece of work on page 2, and we need it to be on page 1, so it's the first thing people see.
Any of the following features would be useful:

- A way to delete a page, so we can get rid of page 1
- A way to re-order the pages, to put page 2 first
- A way to copy/paste between pages
- A way to import from SVG. We can export page 2 to SVG, but can't get it back in

My guess would be that deleting or reordering pages would be the easiest/quickest to implement? Thanks!

**Comment by edemaine** [comment]
Unfortunately, none of these are possible right now. They are, however, represented by existing issues:
* #18
* #18 
* #94 
* #22

If you are using your own server (or otherwise have access to the underlying database), you could easily swap the pages by modifying the `pages` attribute of the `room` document.

Manipulating pages, especially page deletion, is high on my list, but I don't know when I will get to it.

A simple workaround would be to put the text "please go to page 2" on page 1...
