### ISSUE TITLE
Tab characters in text input

### ISSUE THREAD

**Issue by psvenk** [edemaine/cocreate#160]
Currently, pressing `<TAB>` in a text box cycles to another control on the page. It would be useful to have this insert a literal tab character, or alternatively 4 spaces, when writing pseudocode.

**Comment by edemaine** [comment]
That makes sense, though I worry about overriding the tab key for those navigating by keyboard.  That said, Cocreate isn't very usable via keyboard, so perhaps it's fine...?  Perhaps a reasonable alternative is that <kbd>Tab</Kbd> inserts a tab key if this is not the first keyboard interaction with the textarea (e.g. characters have been typed, or arrow keys have been pressed); but it cycles otherwise.  One can use <kbd>Escape</kbd> to get back to cycle mode.

**Comment by edemaine** [comment]
Implemented.  Will be deployed in a little while.

**Comment by psvenk** [comment]
@edemaine Thank you!
