### ISSUE TITLE
Feature request: pan using touchscreen without changing tool

### ISSUE THREAD

**Issue by ianbrody** [edemaine/cocreate#168]
It would be really great if, after disabling drawing with the touch screen, dragging the touchscreen with one's finger would instead pan even when the drawing tool is selected. I know I could change the tool for this, but it's an extra step and I'm used to other drawing apps (e.g. xournalpp, but probably most of the non-web ones) that do this. Second-best would be for two-finger drag to act as panning (this is what awwapp does).

**Comment by edemaine** [comment]
PR #111 is a work-in-progress to address this (two-finger drag specifically). I should try to get to finishing it to at least support this functionality.

I feel like one-finger drag isn't a great idea, because it would be easy to accidentally drag while using the pen and resting your palm.  (Some tablets aren't perfect at palm rejection.)

**Comment by edemaine** [comment]
2-finger drag with touch drawing disabled is now implemented. (A while ago actually; I forgot this was a separate issue.)
