### ISSUE TITLE
Undo should select

### ISSUE THREAD

**Issue by edemaine** [edemaine/cocreate#47]
Undoing/redoing some/all operations (e.g. edits) should probably select those objects that changed, so it's easy to continue changes. (Illustrator does this, for example.)

This at least makes sense when `select` tool is currently active. I'm not sure what it means when e.g. `pen` tool is active, in which case e.g. selecting a color would change the current pen color, not the selected objects.  So maybe this auto-selection should happen only when `select` is currently selected. (This is when undo would likely involve edit operations anyway.)

**Comment by adqm** [comment]
This is interesting to me.  I think it's not hard to implement regardless, but it's worth thinking about what is the right metric here, where people won't be surprised by something being selected (or not) after an undo?  I see several ways that this could potentially be implemented:

1. We could use the _currently-selected_ tool as a way to decide whether to select or not, as you suggest above.

1. We could store whether each action operated on a selection or not as part of the call to `undoableAction`, and select the relevant objects in the case of undoing an action that acted on a selection (selection information stored as part of the action, regardless of the tool that is selected when the "undo" action is taken).

1. We could track changes to the selection as undoable actions.  GIMP does things this way, actions that change the selection are themselves undoable (i.e., the selection is an active object that is considered as part of the state, rather than a separate thing to keep track of).  This is slightly harder to implement if object IDs are not retained after a delete-and-restore operation (I haven't checked to see whether that's the case), but probably still doable.

**Comment by edemaine** [comment]
I think Option 2 is probably best: store the relevant selection when storing the `undoableAction`.  Then, if an undo/redo operation triggers a (nonempty) selection, we switch the current tool to `select`.

If this ends up being confusing, we can easily switch to Option 1 using the currently selected tool to sometimes ignore the action.  But I think it'll be fairly intuitive...

Option 3 is common in photo editing tools (GIMP and Photoshop do it), but I don't think I've ever seen it in a vector drawing tool (Illustrator, Inkscape, CAD, etc.).  Admittedly, it sounds useful, but I fear it'll be too counterintuitive.

I just checked the following behaviors:
* In Illustrator, undo selects the changed objects, but doesn't change the tool. But it has a notion of selected objects when in any tool. For example, changing the pen color ends up changing the selection but not the to-be-drawn objects...
* In Inkscape, undo doesn't select anything (or change tools). I recall finding this really annoying. 🙂

**Comment by adqm** [comment]
Hmmm...I haven't thought about this enough, but I don't think I agree with forcibly changing the tool.  If I'm drawing with the pen, for example, and make a stroke I want to roll back, it would be nice to just ctrl+z and then draw the new thing, rather than having to re-select the pen before drawing.

**Comment by edemaine** [comment]
Ah, that's definitely true. So maybe a mixture of Options 1 and 2 is best, until we define the notion of selection in every tool.

**Comment by edemaine** [comment]
I implemented this. For the most part, I could compute the correct selection from the undoable operation itself; only the new Duplicate functionality required special care. Selection is modified only in the two modes that it currently makes sense: the select tool and the text tool.
