### ISSUE TITLE
keyboard shortcuts for switching tools and widths (and colors?)

### ISSUE THREAD

**Issue by adqm** [edemaine/cocreate#57]
I think this is really easy to implement, but I think it could also be a really big QoL improvement, since changing tools currently requires clicking/tapping on a small button.

I could imagine, for example:

* [x] number keys `1`-`7` change the width
* tools each have an easy keyboard shortcut:
    * [ ] ??? for pan (maybe `m` for "move"?)
    * [x] `s` for select
    * [x] `p` for pen
    * [x] `l` for line
    * [x] `r` for rectangle
    * [x] `o` for ellipse
    * [x] `x` for eraser (Adam originally suggested `e`, but worried about ambiguity with ellipse; previously implemented '-' but that's better used for zoom)
* maybe some other ones, too:
    * [ ] `h` for opening history
    * [ ] `ctrl+s` for saving to SVG

Not sure if it makes sense to try to have something for colors as well...

**Comment by edemaine** [comment]
I agree this is important, but I hadn't done it yet because I think we need a lot of care in choosing the correct keys, because people will quickly memorize and then it'll be hard to change. Maybe I shouldn't worry so much, and feel free to break things in these early beta stages...

Plausibly we should have the keys be customizable, possibly with quick bindings to match Illustrator or Inkscape. I wasn't sure how many key overlaps there would be, but here's an analysis:

Tool | Illustrator | Inkscape
-----|------------|-----------
Pan | <kbd>h</kbd> (hand), or #37 | no analog (<kbd>ctrl</kbd>+drag pans)
Select | <kbd>v</kbd> (pointer) | <kbd>F1</kbd>
Pen | <kbd>n</kbd> (pencil) | <kbd>p</kbd>
Line segment | <kbd>\\</kbd> | no analog (<kbd>b</kbd> is close, but really polylines)
Rectangle | <kbd>m</kbd> | <kbd>r</kbd>
Eraser | no analog (<kbd>shift-e</kbd> is area eraser) | no analog

**Comment by adqm** [comment]
Yeah, I'm usually pretty reckless with things like that, but people do (rightfully) get upset with me because catsoop changes stuff all the time.  So maybe it is indeed good to be a little careful...

I've never used Illustrator, and I don't have a lot of experience with Inkscape, so I'm not too familiar with those.  I was just trying to think through what some sensible defaults might be, from first principles.

I like the idea of making the keybindings customizable (#16), and having a way to quick-select bindings from common vector drawing programs.  I would probably argue that the defaults shouldn't be chosen based on other programs (both of the lists you shared above, and illustrator in particular, just seem _weird_ to me!), but I could see an argument in the other direction.

**Comment by edemaine** [comment]
FYI, most of these are now live (see checklist above). Hope you like them!

**Comment by edemaine** [comment]
I think this can be closed for now, with #16 for custom keyboard shortcuts.  History/time travel isn't particularly usable via a keyboard interface, so it probably doesn't need a shortcut? And I feel like hotkeys are more of a priority for the drawing modes/styles, not the uncommon operations in the bottom left.
