### ISSUE TITLE
fonts and google

### ISSUE THREAD

**Issue by adqm** [edemaine/cocreate#58]
Would it be a welcome change to serve the fonts locally instead of requesting them from Google?  

Individuals can certainly already disable remote font loading within their own browsers, but I think it would be nice if cocreate didn't make any external requests in the course of normal operation.  I think as of right now, it looks like the only external requests are from loading the fonts from Google.

An alternative approach would be simply to change the CSS so that it uses system fonts instead of trying to load a custom font at all.  Given the small amount of text in the coauthor interface, is there really a reason to care if it's rendered in Roboto?

(sorry for the flood of posts here, just trying to get things written down while I'm thinking of them)

**Comment by edemaine** [comment]
Generally, Google Fonts server will have much higher performance (thanks to CDN) than a Meteor server, so this is intentional. It is easy enough to include the fonts in the distribution, but I'm not sure I see the motivation... are you imagining Cocreate running in a LAN environment without Internet access? I guess I could see trying Google, and falling back on a local copy on failure...

Fixing the font helps with layout issues. And stylistically, I like being in control of the font. There isn't much text now, but there *will* be, especially with #7 (text tool), which is probably the most requested feature at the moment.
